input {
  file {
    path => "/var/www/storage/logs/laravel.log"
    start_position => "beginning"
    sincedb_path => "/dev/null"
    type => "laravel"
  }
}

filter {
  grok {
    match => {
      "message" => "\[%{TIMESTAMP_ISO8601:timestamp}\] %{WORD:env}\.%{LOGLEVEL:level}: %{GREEDYDATA:log_message}"
    }
  }
  mutate {
    add_field => { "application" => "suivi_academique_backend" }
  }
}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "laravel-logs-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}
