apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-app
  labels:
    app: laravel
spec:
  replicas: 2
  selector:
    matchLabels:
      app: laravel
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: laravel
    spec:
      containers:
        - name: laravel
          image: laeti2005/suivi_academique_backend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: APP_ENV
              value: "production"
            - name: APP_DEBUG
              value: "true"
            - name: APP_KEY
              value: "base64:DKUe4OS5s/pk0b5ftLntNVT8WBXs/qYK+hTtJAb7Qgk="
            - name: DB_CONNECTION
              value: "mysql"
            - name: DB_HOST
              value: "mysql-service"
            - name: DB_PORT
              value: "3306"
            - name: DB_DATABASE
              value: "laravel"
            - name: DB_USERNAME
              value: "laravel"
            - name: DB_PASSWORD
              value: "root"
            - name: CACHE_STORE
              value: "file"
            - name: SESSION_DRIVER
              value: "file"
            - name: QUEUE_CONNECTION
              value: "sync"
            - name: LOG_CHANNEL
              value: "stderr"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
